### ISSUE TITLE
 Binary XML file line #2: Error inflating class <unknown>

### ISSUE THREAD

**Issue by pdog18** [Ashok-Varma/BottomNavigation#107]
`mBottomBar = (BottomNavigationBar) view.findViewById(R.id.bnb);

        mBottomBar
                .addItem(new BottomNavigationItem(R.drawable.icon, "Home"))
                .addItem(new BottomNavigationItem(R.drawable.icon, "Project"))
                .addItem(new BottomNavigationItem(R.drawable.icon, "Find"))
                .addItem(new BottomNavigationItem(R.drawable.icon, "Center"))
                .initialise();`

```

03-15 17:21:40.986 20543-20543/com.newenergyjinfu.jytz E/AndroidRuntime: FATAL EXCEPTION: 
main
                                                                         Process: com.newenergyjinfu.jytz, PID: 20543
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.newenergyjinfu.jytz/com.newenergyjinfu.jytz.MainActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                          Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                             at com.ashokvarma.bottomnavigation.ShiftingBottomNavigationTab.init(ShiftingBottomNavigationTab.java:47)
                                                                             at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:55)
                                                                             at com.ashokvarma.bottomnavigation.ShiftingBottomNavigationTab.<init>(ShiftingBottomNavigationTab.java:25)
                                                                             at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:393)
                                                                             at com.newenergyjinfu.jytz.fragment.HomeFragment.initBottomBar(HomeFragment.java:127)
                                                                             at com.newenergyjinfu.jytz.fragment.HomeFragment.initView(HomeFragment.java:107)
                                                                             at com.newenergyjinfu.jytz.base.BaseFragment.onCreateView(BaseFragment.java:62)
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                             at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                             at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
                                                                             at android.app.Activity.performStart(Activity.java:6320)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
                                                                          Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:649)
                                                                             at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                             at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                             at com.ashokvarma.bottomnavigation.ShiftingBottomNavigationTab.init(ShiftingBottomNavigationTab.java:47) 
                                                                             at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:55) 
                                                                             at com.ashokvarma.bottomnavigation.ShiftingBottomNavigationTab.<init>(ShiftingBottomNavigationTab.java:25) 
                                                                             at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:393) 
                                                                             at com.newenergyjinfu.jytz.fragment.HomeFragment.initBottomBar(HomeFragment.java:127) 
                                                                             at com.newenergyjinfu.jytz.fragment.HomeFragment.initView(HomeFragment.java:107) 
                                                                             at com.newenergyjinfu.jytz.base.BaseFragment.onCreateView(BaseFragment.java:62) 
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080) 
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108) 
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290) 
                                                                             at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) 
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677) 
                                                                             at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604) 
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238) 
                                                                             at android.app.Activity.performStart(Activity.java:6320) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                             at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                             at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:496) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                             at com.ashokvarma.bottomnavigation.ShiftingBottomNavigationTab.init(ShiftingBottomNavigationTab.java:47) 
                                                                             at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:55) 
                                                                             at com.ashokvarma.bottomnavigation.ShiftingBottomNavigationTab.<init>(ShiftingBottomNavigationTab.java:25) 
                                                                             at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:393) 
                                                                             at com.newenergyjinfu.jytz.fragment.HomeFragment.initBottomBar(HomeFragment.java:127) 
                                                                             at com.newenergyjinfu.jytz.fragment.HomeFragment.initView(HomeFragment.java:107) 
                                                                             at com.newenergyjinfu.jytz.base.BaseFragment.onCreateView(BaseFragment.java:62) 
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080) 
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108) 
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290) 
                                                                             at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) 
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677) 
                                                                             at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604) 
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238) 
                                                                             at android.app.Activity.performStart(Activity.java:6320) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
                                                                          Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f010062 a=-1}
                                                                             at android.content.res.TypedArray.getDrawable(TypedArray.java:869)
                                                                             at android.view.View.<init>(View.java:3955)
                                                                             at android.view.ViewGroup.<init>(ViewGroup.java:574)
                                                                             at android.widget.FrameLayout.<init>(FrameLayout.java:97)
                                                                             at android.widget.FrameLayout.<init>(FrameLayout.java:92)
                                                                             at android.widget.FrameLayout.<init>(FrameLayout.java:88)
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
                                                                             at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                             at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:496) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                             at com.ashokvarma.bottomnavigation.ShiftingBottomNavigationTab.init(ShiftingBottomNavigationTab.java:47) 
                                                                             at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:55) 
                                                                             at com.ashokvarma.bottomnavigation.ShiftingBottomNavigationTab.<init>(ShiftingBottomNavigationTab.java:25) 
                                                                             at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:393) 
                                                                             at com.newenergyjinfu.jytz.fragment.HomeFragment.initBottomBar(HomeFragment.java:127) 
                                                                             at com.newenergyjinfu.jytz.fragment.HomeFragment.initView(HomeFragment.java:107) 
                                                                             at com.newenergyjinfu.jytz.base.BaseFragment.onCreateView(BaseFragment.java:62) 
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080) 
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108) 
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290) 
                                                                             at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) 
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677) 
                                                                             at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604) 
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238) 
                                                                             at android.app.Activity.performStart(Activity.java:6320) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 

```

**Comment by pdog18** [comment]
i try debug into source code;
find error  in the 
class 
`ShiftingBottomNavigationTab`  

method 
`void init()` 

line 47 
` View view = inflater.inflate(R.layout.shifting_bottom_navigation_item, this, true);`


then it jump to `LayoutInflater.java`
method 
`inflate `and break my appilication

how can i use the bottomnavigationbar ?

**Comment by Ashok-Varma** [comment]
can you send your code. xml and all code related to BottomNavBar. There is no error in code. Something in your initialisation might be wrong

**Comment by Ashok-Varma** [comment]
closed due to inactivity

**Comment by pdog18** [comment]
@Ashok-Varma 
when i use theme like this ,change the theme' parent 
```
<!-- Application theme. -->
    <style name="AppTheme" parent="android:Theme.Light">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>
```
the crash can be reappear


//xml
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="com.example.bnbar.MainActivity">

    <com.ashokvarma.bottomnavigation.BottomNavigationBar
        android:id="@+id/bottom_navigation_bar"
        android:layout_width="match_parent"
        android:layout_height="50dp"/>

</LinearLayout>

```

//activity
```
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        BottomNavigationBar bottom_navigation_bar = (BottomNavigationBar) findViewById(R.id.bottom_navigation_bar);


        bottom_navigation_bar
                .addItem(new BottomNavigationItem(R.mipmap.ic_launcher, "首页"))
                .addItem(new BottomNavigationItem(R.mipmap.ic_launcher_round, "投资"))
                .addItem(new BottomNavigationItem(R.mipmap.ic_launcher, "发现"))
                .addItem(new BottomNavigationItem(R.mipmap.ic_launcher_round, "我的"))
                .initialise();
        bottom_navigation_bar.setTabSelectedListener(new BottomNavigationBar.OnTabSelectedListener() {
            @Override
            public void onTabSelected(int position) {
                Log.d("onTabSelected", "postion = " + position);
            }

            @Override
            public void onTabUnselected(int position) {
                Log.d("onTabUnselected", "postion = " + position);
            }

            @Override
            public void onTabReselected(int position) {
                Log.d("onTabReselected", "postion = " + position);
            }
        });
    }
}

```


//manifest
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.example.bnbar">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>

</manifest>
```
