### ISSUE TITLE
crash “Binary XML file line #2: Binary XML file line #2: Error inflating class”

### ISSUE THREAD

**Issue by WardenAndroid** [Ashok-Varma/BottomNavigation#117]
I use this theme when the crash happened  
我使用这个theme的时候发生了奔溃

```
android:theme="@android:style/Theme.Light.NoTitleBar"
```
Refer to the log:  
参考日志：

```
 FATAL EXCEPTION: main
Process: com.example.bottomtest, PID: 27853
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.bottomtest/com.example.bottomtest.EasyHomeMainActivity2}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
```

**Comment by wosika** [comment]
我也遇到了这个问题。在添加 item的时候崩溃了

**Comment by Ashok-Varma** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.bottomtest/com.example.bottomtest.EasyHomeMainActivity2}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>

Issue with some class Unknow exception.can you post your xml here
