### ISSUE TITLE
进入APP, 点击 MODE_FIXED 应用crash

### ISSUE THREAD

**Issue by hjm1fb** [Ashok-Varma/BottomNavigation#123]
05-31 14:58:56.805 13020-13020/com.ashokvarma.bottomnavigation.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.ashokvarma.bottomnavigation.sample, PID: 13020
                                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setBackgroundDrawable(android.graphics.drawable.Drawable)' on a null object reference
                                                                                            at com.ashokvarma.bottomnavigation.BottomNavigationHelper.setShapeBadgeForTab(BottomNavigationHelper.java:166)
                                                                                            at com.ashokvarma.bottomnavigation.BottomNavigationHelper.bindTabWithData(BottomNavigationHelper.java:156)
                                                                                            at com.ashokvarma.bottomnavigation.BottomNavigationBar.setUpTab(BottomNavigationBar.java:497)
                                                                                            at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:386)
                                                                                            at com.ashokvarma.bottomnavigation.sample.HomeActivity.refresh(HomeActivity.java:281)
                                                                                            at com.ashokvarma.bottomnavigation.sample.HomeActivity.onCheckedChanged(HomeActivity.java:185)
                                                                                            at android.widget.CompoundButton.setChecked(CompoundButton.java:161)
                                                                                            at com.ashokvarma.bottomnavigation.sample.HomeActivity.onCheckedChanged(HomeActivity.java:155)
                                                                                            at android.widget.CompoundButton.setChecked(CompoundButton.java:161)
                                                                                            at android.widget.CompoundButton.toggle(CompoundButton.java:120)
                                                                                            at android.widget.CompoundButton.performClick(CompoundButton.java:125)
                                                                                            at android.view.View$PerformClick.run(View.java:21297)
                                                                                            at android.os.Handler.handleCallback(Handler.java:743)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:150)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
05-31 14:58:56.850 3961-4186/? I/logserver: is_all_ready, any file is ready in non-keyfile exception.

**Comment by Ashok-Varma** [comment]
@rpandey91 can you have a look in to this issue

**Comment by Ashok-Varma** [comment]
@hjm1fb please post the XML and code related to bottom navigation. It will be helpful

**Comment by hjm1fb** [comment]
@Ashok-Varma  I downloaded the whole project and run it, no modification. Then that crash happened. The AS version is 2.2.2 , Android version is 6.0. And I remember that days ago, I just run the older version with no problem.

**Comment by rpandey91** [comment]
Thanks Ashok, for fixing it. I was a bit busy with my office work.

Regards,
Rahul

On Jun 24, 2017 1:22 PM, "Ashok Varma" <notifications@github.com> wrote:

Closed #123 <https://github.com/Ashok-Varma/BottomNavigation/issues/123>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Ashok-Varma/BottomNavigation/issues/123#event-1137389563>,
or mute the thread

**Comment by Ashok-Varma** [comment]
@rpandey91 it's ok. i reverted all the previous commits for these features (ShapeDrawable, HideText). Rewrote both features. you can have a look
