### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by JeremyHwc** [Ashok-Varma/BottomNavigation#130]
FATAL EXCEPTION: main
                                                                                        Process: com.ashokvarma.bottomnavigation.sample, PID: 13811
                                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.widget.FrameLayout.getLayoutParams()' on a null object reference 
at com.ashokvarma.bottomnavigation.BottomNavigationTab.setIconLayoutGravityCenter(BottomNavigationTab.java:121)
at com.ashokvarma.bottomnavigation.BottomNavigationBar.setUpTab(BottomNavigationBar.java:501)                                                                                         
at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:386)                                                                                           at com.ashokvarma.bottomnavigation.sample.HomeActivity.refresh(HomeActivity.java:290)                                                                                           at com.ashokvarma.bottomnavigation.sample.HomeActivity.onCheckedChanged(HomeActivity.java:185)                                                                                            at android.widget.CompoundButton.setChecked(CompoundButton.java:156)                                                                                           at com.ashokvarma.bottomnavigation.sample.HomeActivity.onCheckedChanged(HomeActivity.java:158)                                                                                            at android.widget.CompoundButton.setChecked(CompoundButton.java:156)                                                                                           at android.widget.CompoundButton.toggle(CompoundButton.java:115)                                                                                           at android.widget.CompoundButton.performClick(CompoundButton.java:120)                                                                                           at android.view.View$PerformClick.run(View.java:21540)                                                                                           at android.os.Handler.handleCallback(Handler.java:815)                                                                                         at android.os.Handler.dispatchMessage(Handler.java:104)                                                                                           at android.os.Looper.loop(Looper.java:207)                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5710)                                                                                          at java.lang.reflect.Method.invoke(Native Method)                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

I get your answer about NullPointerException,but when I changed the code to (new BottomNavigationItem(R.drawable.main_bottom_profession,"")),It also report NullPointerException and the description is above.

**Comment by J1aDong** [comment]
+1

**Comment by xiayibo** [comment]
+1

**Comment by Ashok-Varma** [comment]
I will look in to it this weekend
