### ISSUE TITLE
branch master, version 1.4.3 was crashed when I was open app

### ISSUE THREAD

**Issue by xianjun-liu** [Ashok-Varma/BottomNavigation#135]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setBackgroundDrawable(android.graphics.drawable.Drawable)' on a null object reference
                                                                       at com.ashokvarma.bottomnavigation.BottomNavigationHelper.setShapeBadgeForTab(BottomNavigationHelper.java:166)
                                                                       at com.ashokvarma.bottomnavigation.BottomNavigationHelper.bindTabWithData(BottomNavigationHelper.java:156)
                                                                       at com.ashokvarma.bottomnavigation.BottomNavigationBar.setUpTab(BottomNavigationBar.java:497)
                                                                       at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:386)
                                                                       at com.tianxi66.test.MainActivity.onCreate(MainActivity.java:34)
                                                                       at android.app.Activity.performCreate(Activity.java:6303)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by Ashok-Varma** [comment]
current branch master_v2 and V2.0.1 mostly all the merges from outside are reverted and i re-wrote the code again. Please try this branch and check
