### ISSUE TITLE
No static field fixed_bottom_navigation_icon_container

### ISSUE THREAD

**Issue by xianjun-liu** [Ashok-Varma/BottomNavigation#136]
java.lang.NoSuchFieldError: No static field fixed_bottom_navigation_icon_container of type I in class Lcom/ashokvarma/bottomnavigation/R$id; or its superclasses (declaration of 'com.ashokvarma.bottomnavigation.R$id' appears in /data/app/com.tianxi66.zxgb-1/base.apk:classes2.dex)
                                                                       at com.ashokvarma.bottomnavigation.FixedBottomNavigationTab.init(FixedBottomNavigationTab.java:52)
                                                                       at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:67)
                                                                       at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:62)
                                                                       at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:58)
                                                                       at com.ashokvarma.bottomnavigation.FixedBottomNavigationTab.<init>(FixedBottomNavigationTab.java:26)
                                                                       at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:394)
                                                                       at com.dx168.zxgb.activity.MainActivity.initBottomNavigationBar(MainActivity.java:220)
                                                                       at com.dx168.zxgb.activity.MainActivity.onCreate(MainActivity.java:75)
                                                                       at android.app.Activity.performCreate(Activity.java:6303)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

how to resovel it !

**Comment by Ashok-Varma** [comment]
which version are you using and send the sample code as well

**Comment by renaldi2108** [comment]
@Ashok-Varma when we get this problem, what should i do ?? Is it because of the version of the gradle I'm using or what ??
