### ISSUE TITLE
sample error at 2.0.1

### ISSUE THREAD

**Issue by chipsCode** [Ashok-Varma/BottomNavigation#139]
**Before the change**
```
dependencies {
   ...
 compile project(':bottom-navigation-bar')
  ...
}
```
**After the change**

```
dependencies {
   ...
compile "com.ashokvarma.android:bottom-navigation-bar:2.0.1"
  ...
}
```
**The error log**
```
07-20 23:14:30.620 392-392/? E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so
                                    
                                    
                                    --------- beginning of crash
07-20 23:14:30.721 7781-7781/com.ashokvarma.bottomnavigation.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.ashokvarma.bottomnavigation.sample, PID: 7781
                                                                                      java.lang.IllegalAccessError: Illegal class access: 'com.ashokvarma.bottomnavigation.sample.HomeActivity' attempting to access 'com.ashokvarma.bottomnavigation.BadgeItem' (declaration of 'com.ashokvarma.bottomnavigation.sample.HomeActivity' appears in /data/app/com.ashokvarma.bottomnavigation.sample-1/base.apk)
                                                                                          at com.ashokvarma.bottomnavigation.sample.HomeActivity.refresh(HomeActivity.kt:198)
                                                                                          at com.ashokvarma.bottomnavigation.sample.HomeActivity.onItemSelected(HomeActivity.kt:160)
                                                                                          at android.widget.AdapterView.fireOnSelected(AdapterView.java:931)
                                                                                          at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:920)
                                                                                          at android.widget.AdapterView.access$300(AdapterView.java:51)
                                                                                          at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:890)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5437)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
07-20 23:14:30.723 2950-3471/? W/ActivityManager:   Force finishing activity com.ashokvarma.bottomnavigation.sample/.HomeActivity
```

**Comment by chipsCode** [comment]
Oh, no problem with 2.0.2
