### ISSUE TITLE
the "com.ashokvarma.android:bottom-navigation-bar:2.0.5" can't start up with API23 and the lower version

### ISSUE THREAD

**Issue by LuckyLee458** [Ashok-Varma/BottomNavigation#195]
when the AVD start up with the API23 and the lower version,the MainActivity throw the java.lang.RuntimeException:android.content.res.Resources$NotFoundException: Resource ID #0x7f060055.

but it is perfect with the API24 and higher version.
I have read the 'readme' file ,but nothing can help.
so,I can't solve the problem right now,please help.

**Comment by Ashok-Varma** [comment]
Can you post more stacktrace ??

**Comment by LuckyLee458** [comment]
Yes,Here is the stacktrace printed in the Logcat:

**at com.example.administrator.myapplication12.MainActivity.onCreate(MainActivity.java:63)
the 63 line in my program is the '.initialise()' function.**
 --------- beginning of crash
09-10 01:05:08.886 4510-4510/com.example.administrator.myapplication12 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.administrator.myapplication12, PID: 4510
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.administrator.myapplication12/com.example.administrator.myapplication12.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f060055
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f060055
        at android.content.res.Resources.getValue(Resources.java:1351)
        at android.content.res.Resources.getDrawable(Resources.java:804)
        at android.content.Context.getDrawable(Context.java:458)
        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:463)
        at com.ashokvarma.bottomnavigation.BottomNavigationItem.getIcon(BottomNavigationItem.java:192)
        at com.ashokvarma.bottomnavigation.BottomNavigationHelper.bindTabWithData(BottomNavigationHelper.java:120)
        at com.ashokvarma.bottomnavigation.BottomNavigationBar.setUpTab(BottomNavigationBar.java:508)
        at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:395)
        at com.example.administrator.myapplication12.MainActivity.onCreate(MainActivity.java:63)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
09-10 01:05:08.887 1947-1959/system_process W/ActivityManager:   Force finishing activity com.example.administrator.myapplication12/.MainActivity
09-10 01:05:09.237 1947-1959/system_process I/WindowManager: Screenshot max retries 4 of Token{2d6e523 ActivityRecord{fe22e52 u0 com.example.administrator.myapplication12/.MainActivity t7 f}} appWin=Window{a6935aa u0 Starting com.example.administrator.myapplication12} drawState=3
09-10 01:05:09.238 1947-1947/system_process W/art: Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 308ms
09-10 01:05:09.295 1947-3575/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
09-10 01:05:09.302 1947-3575/system_process D/EGL_emulation: eglCreateContext: 0xae456700: maj 2 min 0 rcv 2
09-10 01:05:09.303 1947-3575/system_process D/EGL_emulation: eglMakeCurrent: 0xae456700: ver 2 0 (tinfo 0x9b7fffb0)
09-10 01:05:09.322 1947-3575/system_process D/EGL_emulation: eglMakeCurrent: 0xae456700: ver 2 0 (tinfo 0x9b7fffb0)
09-10 01:05:09.322 1947-2703/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-10 01:05:09.325 1947-2199/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-10 01:05:09.358 1947-2201/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-10 01:05:09.739 1947-1961/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{fe22e52 u0 com.example.administrator.myapplication12/.MainActivity t7 f}
09-10 01:05:09.752 1947-2197/system_process I/ActivityManager: Killing 3207:com.google.android.gms.ui/u0a8 (adj 15): empty #17
09-10 01:05:19.793 1947-1961/system_process W/ActivityManager: Activity destroy timeout for ActivityRecord{fe22e52 u0 com.example.administrator.myapplication12/.MainActivity t7 f}
09-10 01:05:25.396 1947-2108/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-10 01:05:55.436 1947-2703/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-10 01:06:00.070 1273-1303/? D/hwcomposer: hw_composer sent 137 syncs in 63s
09-10 01:06:25.474 1947-2200/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-10 01:06:25.501 2878-4537/com.google.android.gms I/GCM-GMS: Registering GMS 745476177629
09-10 01:06:25.515 2838-4298/com.google.android.gms.persistent E/GCM: Missing checkin config file
09-10 01:06:25.515 2838-4298/com.google.android.gms.persistent W/GCM: GCM FAILED TO INITIALIZE - missing checkin
09-10 01:06:25.515 2878-4537/com.google.android.gms W/GCM-GMS: Failed to get registration: java.io.IOException: AUTHENTICATION_FAILED
09-10 01:06:55.527 1947-2200/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-10 01:07:00.064 1273-1303/? D/hwcomposer: hw_composer sent 25 syncs in 60s

**Comment by Ashok-Varma** [comment]
@LuckyLee458 seems like resourse which is sent to library is not available. can you send me your initialisation code
