### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Cannot start this animator on a detached view! 

### ISSUE THREAD

**Issue by WiiliamChik** [Ashok-Varma/BottomNavigation#200]
i get this crash in frabic report. please help.

`Fatal Exception: java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:858)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:277)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:261)
       at android.animation.RevealAnimator.(RevealAnimator.java:37)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:48)
       at com.ashokvarma.bottomnavigation.BottomNavigationHelper.setBackgroundWithRipple(BottomNavigationHelper.java:174)
       at com.ashokvarma.bottomnavigation.BottomNavigationBar$2.run(BottomNavigationBar.java:545)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)`

**Comment by Ashok-Varma** [comment]
can you send me sample setup. Support libraries you are using Etc.

Support libraries are updated in new library version. Please try new library and check once

**Comment by Ashok-Varma** [comment]
It shouldn't cause the issue. But it can be anyway next week I am moving the libraries to Androidx. you guys can update to that
