### ISSUE TITLE
It is in conflict with other libraries i think

### ISSUE THREAD

**Issue by EpsilonOrionis** [Ashok-Varma/BottomNavigation#32]
When I add this library I get a ClassDefNotFoundError in another library, if I don't use this library everything works. How's it possible? Only with preLollipop devices

**Comment by Ashok-Varma** [comment]
@EpsilonOrionis can you send me the exact Log. i will let you know the issue

**Comment by EpsilonOrionis** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        java.lang.NoClassDefFoundError: org.joda.time.tz.ZoneInfoProvider
                                                                            at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:514)
                                                                            at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:413)
                                                                            at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:349)
                                                                            at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:157)
                                                                            at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
                                                                            at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:61)
                                                                            at org.joda.time.DateTime.<init>(DateTime.java:171)
                                                                            at com.test.orion.pippo.activities.ExampleActivity$2$2.onDateSet(ExampleActivity.java:212)
                                                                            at com.wdullaer.materialdatetimepicker.date.DatePickerDialog.notifyOnDateListener(DatePickerDialog.java:928)
                                                                            at com.wdullaer.materialdatetimepicker.date.DatePickerDialog$1.onClick(DatePickerDialog.java:325)
                                                                            at android.view.View.performClick(View.java:4279)
                                                                            at android.view.View$PerformClick.run(View.java:17659)
                                                                            at android.os.Handler.handleCallback(Handler.java:725)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                            at android.os.Looper.loop(Looper.java:137)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:511)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by Ashok-Varma** [comment]
@EpsilonOrionis i don't think it's this library issue.

If you enable progaurd this might happen. It's other library's issue you can check this link : https://github.com/dlew/joda-time-android/issues/36

**Comment by Ashok-Varma** [comment]
@EpsilonOrionis is it fixed ??

**Comment by EpsilonOrionis** [comment]
Yes, it was a multidexing problem

**Comment by Ashok-Varma** [comment]
@EpsilonOrionis thanks for conforming.
