### ISSUE TITLE
Programmatically click on a tab

### ISSUE THREAD

**Issue by asebak** [Ashok-Varma/BottomNavigation#6]
How to programatically click on a tab?

**Comment by Ashok-Varma** [comment]
@asebak 
you can call method selectTab(newPosition) on bottomNavigationBar.

These are the two methods you can use : 

```java
    /**
     * @param newPosition to select a tab after bottom navigation bar is initialised
     */
    public void selectTab(int newPosition) {
    }

    /**
     * @param newPosition  to select a tab after bottom navigation bar is initialised
     * @param callListener should this change call listener callbacks
     */
    public void selectTab(int newPosition, boolean callListener) {
    }
```

**Comment by asebak** [comment]
@Ashok-Varma thanks a lot

**Comment by asebak** [comment]
@Ashok-Varma I tried that and get the following error:
`    Caused by: java.lang.IllegalStateException: Cannot start this animator on a detached view!
                                                                                         at android.view.RenderNode.addAnimator(RenderNode.java:858)
                                                                                         at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:277)
                                                                                         at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:261)
                                                                                         at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
                                                                                         at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:48)
                                                                                         at com.ashokvarma.bottomnavigation.BottomNavigationHelper.setBackgroundWithRipple(BottomNavigationHelper.java:156)
                                                                                         at com.ashokvarma.bottomnavigation.BottomNavigationBar.selectTabInternal(BottomNavigationBar.java:412)
                                                                                         at com.ashokvarma.bottomnavigation.BottomNavigationBar.selectTab(BottomNavigationBar.java:385)
                                                                                         at com.ashokvarma.bottomnavigation.BottomNavigationBar.selectTab(BottomNavigationBar.java:377)
                                                                                         at`

**Comment by Ashok-Varma** [comment]
@asebak 
Two Cases : 
1) if you want to select a tab immediately on app open : you can set it using setFirstSelectedPosition before calling initialise on bottomNavigationBar.
 2) once initialise is called then if you want to select a tab, you need to use one these two methods.

Thanks for reporting the bug i will fix it in next update. For now you can follow cases mentioned above based on your requirement. 
If you still facing the issue even after following the points mentioned above let me know

**Comment by asebak** [comment]
It doesnt work, I tried using setFirstSelectedPosition(1)

when I use   bottomNavigationBar.selectTab(1, true); it never calls the listener and the second parameter is true

**Comment by Ashok-Varma** [comment]
@asebak 
can you post your code to setup bottomBar. So i can check where it went wrong.

**Comment by asebak** [comment]
`  bottomNavigationBar = (BottomNavigationBar) findViewById(R.id.bottom_navigation_bar);

        if (bottomNavigationBar != null) {
                bottomNavigationBar.addItem(new BottomNavigationItem(x0,y0)
            bottomNavigationBar.addItem(new BottomNavigationItem(x1,y1)
            bottomNavigationBar.addItem(new BottomNavigationItem(x2,y2)
                 bottomNavigationBar.setMode(BottomNavigationBar.MODE_CLASSIC)
                    .setBackgroundStyle(BottomNavigationBar.BACKGROUND_STYLE_RIPPLE)
                    .setFirstSelectedPosition(1)
                    .initialise();

            bottomNavigationBar.setTabSelectedListener(new BottomNavigationBar.OnTabSelectedListener() {

                @Override
                public void onTabSelected(int position) {
                }

                @Override
                public void onTabUnselected(int position) {
                }

                @Override
                public void onTabReselected(int position) {
                }
            });
           bottomNavigationBar.selectTab(1, true);

onTabSelected doesn't get called

**Comment by Ashok-Varma** [comment]
@asebak 

since you already set setFirstSelectedPosition to 1, current selected position is 1. so if you call ```selectTab(1, true)``` then onTabReslected will be called.

So remove setFirstSelectedPosition then onTabSelected will be called

**Comment by Ashok-Varma** [comment]
@asebak is it working ?? 
i am closing the issue if it is not working reopen and let me know and update library to 1.1.1. I already pushed it and i will update Read.me soon thankyou
