### ISSUE TITLE
Throw error on before snack bar dismiss

### ISSUE THREAD

**Issue by silverboyir** [Ashok-Varma/BottomNavigation#66]
Hi
i updated support design and other google view libs , now before dismissing the snackbar app throw an error 
`java.lang.IndexOutOfBoundsException: Invalid index 6, size is 6
                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                     at java.util.ArrayList.get(ArrayList.java:308)
                                                     at android.support.design.widget.CoordinatorLayout.onChildViewsChanged(CoordinatorLayout.java:1280)
                                                     at android.support.design.widget.CoordinatorLayout$HierarchyChangeListener.onChildViewRemoved(CoordinatorLayout.java:2863)
                                                     at android.view.ViewGroup.onViewRemoved(ViewGroup.java:3856)
                                                     at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4238)
                                                     at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4193)
                                                     at android.view.ViewGroup.removeView(ViewGroup.java:4124)
                                                     at android.support.design.widget.Snackbar.onViewHidden(Snackbar.java:646)
                                                     at android.support.design.widget.Snackbar.access$300(Snackbar.java:72)
                                                     at android.support.design.widget.Snackbar$9.onAnimationEnd(Snackbar.java:588)
                                                     at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
                                                     at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1116)
                                                     at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1171)
                                                     at android.animation.ValueAnimator.cancel(ValueAnimator.java:1073)
                                                     at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:967)
                                                     at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:923)
                                                     at android.view.ViewPropertyAnimator.translationY(ViewPropertyAnimator.java:634)
                                                     at android.support.v4.view.ViewPropertyAnimatorCompatICS.translationY(ViewPropertyAnimatorCompatICS.java:38)
                                                     at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.translationY(ViewPropertyAnimatorCompat.java:384)
                                                     at android.support.v4.view.ViewPropertyAnimatorCompat.translationY(ViewPropertyAnimatorCompat.java:757)
                                                     at com.ashokvarma.bottomnavigation.behaviour.BottomVerticalScrollBehavior.updateSnackBarPosition(BottomVerticalScrollBehavior.java:79)
                                                     at com.ashokvarma.bottomnavigation.behaviour.BottomVerticalScrollBehavior.updateSnackBarPosition(BottomVerticalScrollBehavior.java:74)
                                                     at com.ashokvarma.bottomnavigation.behaviour.BottomVerticalScrollBehavior.onDependentViewChanged(BottomVerticalScrollBehavior.java:66)
                                                     at android.support.design.widget.CoordinatorLayout.onChildViewsChanged(CoordinatorLayout.java:1302)
                                                     at android.support.design.widget.CoordinatorLayout$OnPreDrawListener.onPreDraw(CoordinatorLayout.java:1812)
                                                     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1970)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by silverboyir** [comment]
seems problem is for FloatingActionButton and setFab method, if i not setFab , then will not have any problem

**Comment by silverboyir** [comment]
This library is not compatible with com.android.support:design:24.2.0
i downgraded to 24.1.1 , and its work again

**Comment by Ashok-Varma** [comment]
@silverboyir  i will check the issue

**Comment by droidery** [comment]
See https://code.google.com/p/android/issues/detail?id=220762

**Comment by Ashok-Varma** [comment]
i will check with samples and it would be really helpful if you guys can create a pull request updating the sample project to reproduce the issue. So i can directly check the issue instead of trying to reproduce it.
