### ISSUE TITLE
initialise() falls

### ISSUE THREAD

**Issue by devgor88** [Ashok-Varma/BottomNavigation#68]
`FATAL EXCEPTION: main
                                                                      Process: com.kechinde.likeber, PID: 20343
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kechinde.likeber/com.kechinde.likeber.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                          at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                                                                          at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
                                                                          at android.view.LayoutInflater.inflate(Native Method)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                          at com.ashokvarma.bottomnavigation.FixedBottomNavigationTab.init(FixedBottomNavigationTab.java:47)
                                                                          at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:55)
                                                                          at com.ashokvarma.bottomnavigation.FixedBottomNavigationTab.<init>(FixedBottomNavigationTab.java:25)
                                                                          at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:381)
                                                                          at com.kechinde.likeber.MainActivity.tab(MainActivity.java:35)
                                                                          at com.kechinde.likeber.MainActivity.onCreate(MainActivity.java:20)
                                                                          at android.app.Activity.performCreate(Activity.java:5264)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                          at android.os.Looper.loop(Looper.java:193) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                          at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                                                                          at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 
                                                                          at android.view.LayoutInflater.inflate(Native Method) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                          at com.ashokvarma.bottomnavigation.FixedBottomNavigationTab.init(FixedBottomNavigationTab.java:47) 
                                                                          at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:55) 
                                                                          at com.ashokvarma.bottomnavigation.FixedBottomNavigationTab.<init>(FixedBottomNavigationTab.java:25) 
                                                                          at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:381) 
                                                                          at com.kechinde.likeber.MainActivity.tab(MainActivity.java:35) 
                                                                          at com.kechinde.likeber.MainActivity.onCreate(MainActivity.java:20) 
                                                                          at android.app.Activity.performCreate(Activity.java:5264) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                          at android.os.Looper.loop(Looper.java:193) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010064 a=-1}
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:2124)
                                                                          at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                          at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:965)
                                                                          at android.view.View.<init>(View.java:3579)
                                                                          at android.view.ViewGroup.<init>(ViewGroup.java:494)
                                                                          at android.widget.FrameLayout.<init>(FrameLayout.java:114)
                                                                          at android.widget.FrameLayout.<init>(FrameLayout.java:109)
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                          at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                                                                          at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 
                                                                          at android.view.LayoutInflater.inflate(Native Method) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                          at com.ashokvarma.bottomnavigation.FixedBottomNavigationTab.init(FixedBottomNavigationTab.java:47) 
                                                                          at com.ashokvarma.bottomnavigation.BottomNavigationTab.<init>(BottomNavigationTab.java:55) 
                                                                          at com.ashokvarma.bottomnavigation.FixedBottomNavigationTab.<init>(FixedBottomNavigationTab.java:25) 
                                                                          at com.ashokvarma.bottomnavigation.BottomNavigationBar.initialise(BottomNavigationBar.java:381) 
                                                                          at com.kechinde.likeber.MainActivity.tab(MainActivity.java:35) 
                                                                          at com.kechinde.likeber.MainActivity.onCreate(MainActivity.java:20) 
                                                                          at android.app.Activity.performCreate(Activity.java:5264) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                          at android.os.Looper.loop(Looper.java:193) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                                          at dalvik.system.NativeStart.main(Native Method) `

**Comment by devgor88** [comment]
`package com.kechinde.likeber;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import com.ashokvarma.bottomnavigation.BottomNavigationBar;
import com.ashokvarma.bottomnavigation.BottomNavigationItem;
import com.vk.sdk.VKAccessToken;
import com.vk.sdk.VKCallback;
import com.vk.sdk.VKSdk;
import com.vk.sdk.api.VKError;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (VKSdk.isLoggedIn()) {
            tab();
        } else {
            setContentView(R.layout.main);
        }

    }

    protected void tab() {
        setContentView(R.layout.main_interface);
        BottomNavigationBar bottomNavigationBar = (BottomNavigationBar) findViewById(R.id.bottom_navigation_bar);

        bottomNavigationBar
                .addItem(new BottomNavigationItem(R.drawable.ic_iconber, "1"))
                .addItem(new BottomNavigationItem(R.drawable.ic_tab_image2, "2"))
                .addItem(new BottomNavigationItem(R.drawable.ic_tab_image3, "3"))
                .initialise();
        bottomNavigationBar.setTabSelectedListener(new BottomNavigationBar.OnTabSelectedListener() {
            @Override
            public void onTabSelected(int position) {
            }

            @Override
            public void onTabUnselected(int position) {
            }

            @Override
            public void onTabReselected(int position) {
            }
        });
        /*BottomBar bottomBar = (BottomBar) findViewById(R.id.bottomBar);
        bottomBar.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelected(@IdRes int tabId) {
                switch (tabId) {
                    case R.id.bb_tab_1:
                        onTab1();
                        break;
                    case R.id.bb_tab_2:
                        onTab2();
                        break;
                    case R.id.bb_tab_3:
                        onTab3();
                        break;
                }
            }
        });

        bottomBar.setOnTabReselectListener(new OnTabReselectListener() {
            @Override
            public void onTabReSelected(@IdRes int tabId) {

            }
        });*/
    }

    protected void onTab1() {

    }

    protected void onTab2() {

    }

    protected void onTab3() {

    }

    public void login(View v) {
        VKSdk.login(MainActivity.this, "OFFLINE", "WALL");
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!VKSdk.onActivityResult(requestCode, resultCode, data, new VKCallback<VKAccessToken>() {
            @Override
            public void onResult(VKAccessToken res) {
                tab();
            }

            @Override
            public void onError(VKError error) {

            }
        })) {
            super.onActivityResult(requestCode, resultCode, data);
        }
    }
}
`

**Comment by devgor88** [comment]
`package com.kechinde.likeber;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import com.ashokvarma.bottomnavigation.BottomNavigationBar;
import com.ashokvarma.bottomnavigation.BottomNavigationItem;
import com.vk.sdk.VKAccessToken;
import com.vk.sdk.VKCallback;
import com.vk.sdk.VKSdk;
import com.vk.sdk.api.VKError;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (VKSdk.isLoggedIn()) {
            tab();
        } else {
            setContentView(R.layout.main);
        }

    }

    protected void tab() {
        setContentView(R.layout.main_interface);
        BottomNavigationBar bottomNavigationBar = (BottomNavigationBar) findViewById(R.id.bottom_navigation_bar);

        bottomNavigationBar
                .addItem(new BottomNavigationItem(R.drawable.ic_iconber, "1"))
                .addItem(new BottomNavigationItem(R.drawable.ic_tab_image2, "2"))
                .addItem(new BottomNavigationItem(R.drawable.ic_tab_image3, "3"))
                .initialise();
        bottomNavigationBar.setTabSelectedListener(new BottomNavigationBar.OnTabSelectedListener() {
            @Override
            public void onTabSelected(int position) {
            }

            @Override
            public void onTabUnselected(int position) {
            }

            @Override
            public void onTabReselected(int position) {
            }
        });
        /*BottomBar bottomBar = (BottomBar) findViewById(R.id.bottomBar);
        bottomBar.setOnTabSelectListener(new OnTabSelectListener() {
            @Override
            public void onTabSelected(@IdRes int tabId) {
                switch (tabId) {
                    case R.id.bb_tab_1:
                        onTab1();
                        break;
                    case R.id.bb_tab_2:
                        onTab2();
                        break;
                    case R.id.bb_tab_3:
                        onTab3();
                        break;
                }
            }
        });

        bottomBar.setOnTabReselectListener(new OnTabReselectListener() {
            @Override
            public void onTabReSelected(@IdRes int tabId) {

            }
        });*/
    }

    protected void onTab1() {

    }

    protected void onTab2() {

    }

    protected void onTab3() {

    }

    public void login(View v) {
        VKSdk.login(MainActivity.this, "OFFLINE", "WALL");
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!VKSdk.onActivityResult(requestCode, resultCode, data, new VKCallback<VKAccessToken>() {
            @Override
            public void onResult(VKAccessToken res) {
                tab();
            }

            @Override
            public void onError(VKError error) {

            }
        })) {
            super.onActivityResult(requestCode, resultCode, data);
        }
    }
}
`

**Comment by devgor88** [comment]
[MainActivity.txt](https://github.com/Ashok-Varma/BottomNavigation/files/465513/MainActivity.txt)

**Comment by devgor88** [comment]
[main_interface.txt](https://github.com/Ashok-Varma/BottomNavigation/files/465515/main_interface.txt)

**Comment by devgor88** [comment]
Falls on call initialise(), without this call app works properly, but without bottom bar

**Comment by devgor88** [comment]
Sorry, but I will use another Bottom Bar.
